services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --timeout 300 --bind 0.0.0.0:8000 django_app_auth.wsgi:application
    volumes:
      - ./red-social-web:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@db:3312/${DB_DATABASE}

    expose:
      - '8000'
    networks:
      - app-network

networks:
  app-network:
    external: true
